### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by okywijaya** [parsajiravand/my_cv#5]
Sorry sir @parsajiravand , i get problem again with cors in backend.
Do you solution about that?
I create my backend with CodeIgniter 4.  
I try Get, Post the backend with postman is no problem.
I try Get the value from vue Js is working.
But when I post from vue js.
![image](https://user-images.githubusercontent.com/47132213/188442427-4ca7d7e5-ca67-4f5a-af27-e660944c0fc9.png)

Thank you for your attention.

**Comment by parsajiravand** [comment]
@okywijaya 
you should **Access-Control-Allow-Origin: ***
in your backend (Server) code
